version: "3.8"

services:
  app:
    image: my-app:latest
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
    volumes:
      - app-data:/usr/src/app/data
    secrets:
      - app_secret
    environment:
      - APP_SECRET_FILE=/run/secrets/app_secret

  db:
    image: postgres:15
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: mydatabase
    secrets:
      - db_password

volumes:
  app-data:
    driver: local
  db-data:
    driver: local

secrets:
  app_secret:
    file: ./secrets/app_secret.txt
  db_password:
    file: ./secrets/db_password.txt
