version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge